version: "3.9"

services:
  web:
    build:
      context: ./WebChecker
      dockerfile: Dockerfile
    container_name: wocsa_web
    ports:
      - "0.0.0.0:8000:5000"  # Bind port 5000 du container sur toutes les interfaces de l'hôte
    environment:
      README_PATH: /project/README.md
      WEB_HOST: 0.0.0.0
      WEB_PORT: 5000
    volumes:
      - ./README.md:/project/README.md:ro
    restart: unless-stopped

  challenge1:
    build: ./ServerChallenge/challenge1
    container_name: challenge1
    ports:
      - "9001:5000"
    networks:
      - ctfnet

  challenge2:
    build: ./ServerChallenge/challenge2
    container_name: challenge2
    ports:
      - "9002:5000"
    networks:
      - ctfnet

  challenge3:
    build: ./ServerChallenge/challenge3
    container_name: challenge3
    ports:
      - "9999:5000"
    networks:
      - ctfnet

  challenge4:
    build: ./ServerChallenge/challenge4
    container_name: challenge4
    ports:
      - "9003:5000"
    networks:
      - ctfnet
  
  challenge5:
    build: ./ServerChallenge/challenge5
    container_name: challenge5
    ports: 
      - "9004:5000"
    networks:
      - ctfnet


networks:
  ctfnet:
    driver: bridge

